import { useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, Check, ClipboardCheck, Feather, LogOut, Menu, Scale, ShieldCheck, Sparkles, X } from 'lucide-react'

const API_BASE = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000'

async function request(path, options = {}) {
  const token = sessionStorage.getItem('second-opinion-token')
  const response = await fetch(`${API_BASE}${path}`, {
    headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    ...options,
  })
  const body = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(body.error || 'Something went wrong. Please try again.')
  return body
}

function Logo() {
  return <Link to="/" className="flex items-center gap-3" aria-label="Second Opinion home"><span className="logo-mark"><Feather size={18} strokeWidth={2.5} /></span><span className="font-serif text-lg font-semibold tracking-tight">second opinion</span></Link>
}

function Nav({ user, onLogout }) {
  const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-20 border-b border-ink/10 bg-cream/90 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Logo /><button className="rounded-full p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X size={20} /> : <Menu size={20} />}</button><nav className={`${open ? 'flex' : 'hidden'} absolute inset-x-4 top-16 flex-col gap-2 rounded-2xl border border-ink/10 bg-cream p-3 shadow-xl md:static md:flex md:flex-row md:items-center md:gap-2 md:border-0 md:bg-transparent md:p-0 md:shadow-none`}>{user ? <><Link onClick={() => setOpen(false)} className="nav-link" to="/review">Review a product</Link><Link onClick={() => setOpen(false)} className="nav-link" to="/compare">Compare products</Link><button onClick={onLogout} className="nav-link flex items-center gap-2 text-left"><LogOut size={15} /> Sign out</button></> : <><Link onClick={() => setOpen(false)} className="nav-link" to="/login">Log in</Link><Link onClick={() => setOpen(false)} className="button button-dark" to="/signup">Get started <ArrowRight size={16} /></Link></>}</nav></div></header>
}

function Shell({ children, user, onLogout }) { return <div className="min-h-screen bg-cream text-ink"><Nav user={user} onLogout={onLogout} />{children}<footer className="mx-auto flex max-w-6xl flex-col gap-3 border-t border-ink/10 px-5 py-8 text-sm text-ink/55 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>Thoughtful decisions, without the noise.</span><span>© 2026 second opinion</span></footer></div> }

function AuthPage({ mode, onAuth }) {
  const navigate = useNavigate(); const isLogin = mode === 'login'; const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const data = await request(`/api/auth/${isLogin ? 'login' : 'signup'}`, { method: 'POST', body: JSON.stringify(form) }); onAuth(data); navigate('/review') } catch (err) { setError(err.message) } finally { setBusy(false) } }
  return <main className="mx-auto flex min-h-[calc(100vh-72px)] max-w-6xl items-center px-5 py-12 lg:px-8"><div className="grid w-full gap-12 lg:grid-cols-[1fr_420px] lg:items-center"><div className="hidden lg:block"><p className="eyebrow">A calmer way to choose</p><h1 className="display max-w-xl">Make room for a <em>second thought.</em></h1><p className="mt-6 max-w-md text-lg leading-8 text-ink/65">We read between the stars, spot the red flags, and help you decide with a little more confidence.</p></div><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="paper-card"><div className="mb-8"><div className="mb-5 flex size-12 items-center justify-center rounded-2xl bg-amber text-cream"><Sparkles size={21} /></div><h1 className="font-serif text-3xl font-semibold">{isLogin ? 'Welcome back' : 'Start thinking clearly'}</h1><p className="mt-2 text-sm leading-6 text-ink/60">{isLogin ? 'Pick up where you left off.' : 'Create your free account and make your next decision a better one.'}</p></div><form onSubmit={submit} className="flex flex-col gap-4">{!isLogin && <label className="field">Your name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Alex Morgan" /></label>}<label className="field">Email address<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label className="field">Password<input required minLength={6} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" /></label>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="button button-dark mt-2 w-full justify-center">{busy ? 'Working...' : isLogin ? 'Log in' : 'Create account'} <ArrowRight size={17} /></button></form><p className="mt-6 text-center text-sm text-ink/55">{isLogin ? 'New here?' : 'Already have an account?'} <Link className="font-semibold text-brown underline underline-offset-4" to={isLogin ? '/signup' : '/login'}>{isLogin ? 'Create an account' : 'Log in'}</Link></p></motion.div></div></main>
}

function HomePage() { return <main><section className="hero mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pb-28 lg:pt-24"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><p className="eyebrow"><span className="eyebrow-dot" /> Your thoughtful buying companion</p><h1 className="display mt-5 max-w-3xl">The review <em>behind</em> the review.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-ink/65">Second Opinion helps you see past the stars. Understand what is genuine, what is noise, and whether something is actually worth your money.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link className="button button-dark" to="/signup">Find your answer <ArrowRight size={17} /></Link><a className="button button-light" href="#how-it-works">See how it works</a></div></motion.div><motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: .15, duration: .7 }} className="relative"><div className="hero-note"><div className="mb-8 flex items-center justify-between"><span className="text-sm font-semibold">Decision brief</span><span className="rounded-full bg-cream px-3 py-1 text-xs text-brown">just for you</span></div><div className="flex items-end gap-4"><div><span className="text-xs uppercase tracking-[.18em] text-ink/45">confidence</span><div className="mt-2 font-serif text-6xl text-brown">84<span className="text-3xl">%</span></div></div><div className="mb-3 h-16 w-px bg-ink/15" /><p className="mb-2 max-w-[170px] text-sm leading-6 text-ink/65">The signal is stronger than the noise.</p></div><div className="mt-8 flex items-center gap-3 border-t border-ink/10 pt-5 text-sm"><ShieldCheck size={18} className="text-amber" /> <span>Built for honest decisions</span></div></div><div className="absolute -bottom-5 -left-4 flex items-center gap-2 rounded-full border border-ink/10 bg-white px-4 py-3 text-sm shadow-lg sm:-left-8"><ClipboardCheck size={16} className="text-amber" /> Not just another star rating</div></motion.div></section><section id="how-it-works" className="border-y border-ink/10 bg-white/45"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:grid-cols-3 lg:px-8"><Step number="01" title="Bring the question" text="Paste a review that made you pause, or bring two products you cannot choose between." /><Step number="02" title="We read deeper" text="Our analysis looks for sentiment, authenticity signals, useful pros, and the things reviews leave out." /><Step number="03" title="Choose with clarity" text="Get a short, human-readable brief that helps you move forward without second-guessing." /></div></section></main> }
function Step({ number, title, text }) { return <div className="border-l border-ink/15 pl-5"><span className="font-mono text-xs tracking-[.2em] text-amber">{number}</span><h2 className="mt-5 font-serif text-2xl font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-ink/60">{text}</p></div> }

function Protected({ user, children }) { return user ? children : <Navigate to="/login" replace /> }

function AnalysisOverlay({ label }) {
  return <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 flex items-center justify-center bg-ink/35 p-5 backdrop-blur-md"><motion.div initial={{ scale: .92, y: 12 }} animate={{ scale: 1, y: 0 }} className="paper-card flex w-full max-w-sm flex-col items-center gap-5 py-10 text-center"><div className="analysis-spinner"><span /></div><div><p className="eyebrow justify-center">A moment to think</p><h2 className="mt-3 font-serif text-2xl font-semibold">{label}</h2><p className="mt-2 text-sm leading-6 text-ink/55">We&apos;re looking past the obvious signals.</p></div></motion.div></motion.div>
}

function ReviewPage({ setResult }) { const [form, setForm] = useState({ productName: '', productLink: '', reviewText: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate(); async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/api/reviews', { method: 'POST', body: JSON.stringify(form) }); setResult({ type: 'review', data }); navigate('/result') } catch (err) { setError(err.message) } finally { setBusy(false) } } return <Workspace eyebrow="01 / Single review" title="Let’s look at this one together." description="Paste the review that made you hesitate. We’ll separate the useful signal from the marketing fog."><form onSubmit={submit} className="paper-card flex flex-col gap-5"><label className="field">Product name<input value={form.productName} onChange={e => setForm({ ...form, productName: e.target.value })} placeholder="e.g. Everyday Carry Backpack" /></label><label className="field">Product link <span className="font-normal text-ink/40">(optional)</span><input type="url" value={form.productLink} onChange={e => setForm({ ...form, productLink: e.target.value })} placeholder="https://..." /></label><label className="field">Review text<textarea required minLength={10} value={form.reviewText} onChange={e => setForm({ ...form, reviewText: e.target.value })} placeholder="Paste the full review here..." /></label>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="flex flex-col-reverse gap-3 border-t border-ink/10 pt-5 sm:flex-row sm:justify-end"><button type="button" onClick={() => setForm({ productName: '', productLink: '', reviewText: '' })} className="button button-light">Reset</button><button disabled={busy} className="button button-dark">{busy ? 'Reading the review...' : 'Analyze review'} <ArrowRight size={17} /></button></div></form><AnimatePresence>{busy && <AnalysisOverlay label="Reading every signal" />}</AnimatePresence></Workspace> }

function ComparePage({ setResult }) { const [form, setForm] = useState({ a: { name: '', link: '', reviewText: '' }, b: { name: '', link: '', reviewText: '' } }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const navigate = useNavigate(); function update(side, key, value) { setForm({ ...form, [side]: { ...form[side], [key]: value } }) } async function submit(e) { e.preventDefault(); setBusy(true); setError(''); try { const data = await request('/api/comparisons', { method: 'POST', body: JSON.stringify({ productA: form.a, productB: form.b }) }); setResult({ type: 'comparison', data }); navigate('/result') } catch (err) { setError(err.message) } finally { setBusy(false) } } return <Workspace eyebrow="02 / Compare" title="Two options. One clearer answer." description="Give both products an honest read. We’ll put their strengths side by side and help you find the better fit."><form onSubmit={submit} className="grid gap-5 lg:grid-cols-2"><ProductPanel label="Product A" values={form.a} update={(key, value) => update('a', key, value)} /><ProductPanel label="Product B" values={form.b} update={(key, value) => update('b', key, value)} /><div className="flex flex-col gap-3 lg:col-span-2">{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<div className="flex flex-col-reverse gap-3 border-t border-ink/10 pt-5 sm:flex-row sm:justify-between"><button type="button" onClick={() => setForm({ a: { name: '', link: '', reviewText: '' }, b: { name: '', link: '', reviewText: '' } })} className="button button-light">Reset both</button><button disabled={busy} className="button button-dark">{busy ? 'Comparing...' : 'Compare products'} <Scale size={17} /></button></div></div></form><AnimatePresence>{busy && <AnalysisOverlay label="Finding the better fit" />}</AnimatePresence></Workspace> }
function ProductPanel({ label, values, update }) { return <div className="paper-card flex flex-col gap-5"><div className="flex items-center justify-between"><span className="eyebrow !mb-0">{label}</span><span className="rounded-full bg-cream px-3 py-1 text-xs text-ink/45">required</span></div><label className="field">Product name<input required value={values.name} onChange={e => update('name', e.target.value)} placeholder="Product name" /></label><label className="field">Product link <span className="font-normal text-ink/40">(optional)</span><input type="url" value={values.link} onChange={e => update('link', e.target.value)} placeholder="https://..." /></label><label className="field">Review text<textarea required minLength={10} value={values.reviewText} onChange={e => update('reviewText', e.target.value)} placeholder="Paste a review..." /></label></div> }
function Workspace({ eyebrow, title, description, children }) { return <main className="mx-auto max-w-6xl px-5 py-12 lg:px-8 lg:py-20"><div className="mb-10 max-w-2xl"><p className="eyebrow">{eyebrow}</p><h1 className="display mt-4 text-5xl">{title}</h1><p className="mt-5 text-base leading-7 text-ink/60">{description}</p></div>{children}</main> }

function ResultPage({ result }) { const navigate = useNavigate(); if (!result) return <Navigate to="/review" replace />; const { data, type } = result; const isComparison = type === 'comparison'; const review = isComparison ? null : data; const score = review?.fakeReviewScore; return <main className="mx-auto max-w-6xl px-5 py-12 lg:px-8 lg:py-20"><motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="mx-auto max-w-4xl"><div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">03 / Your brief</p><h1 className="display mt-4 text-5xl">Here’s the clearer picture.</h1></div><button onClick={() => navigate(isComparison ? '/compare' : '/review')} className="button button-light self-start">Start again</button></div>{isComparison ? <ComparisonResult data={data} /> : <ReviewResult data={review} score={score} />}</motion.div></main> }
function ReviewResult({ data, score }) { const sentiment = data.overallSentiment || 'mixed'; return <div className="result-stack"><div className="result-hero"><div><span className="eyebrow !text-cream/60">{data.productName || 'Product review'}</span><h2 className="mt-4 max-w-2xl font-serif text-3xl font-semibold text-cream sm:text-4xl">{data.honestSummary || 'A thoughtful read on this product.'}</h2></div><div className="score"><span>signal</span><strong>{score ?? '—'}<small>%</small></strong></div></div><div className="grid gap-5 md:grid-cols-2"><Insight title="What feels genuine" items={data.genuinePros} tone="good" /><Insight title="Worth keeping in mind" items={data.genuineCons} tone="soft" /></div><div className="paper-card"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-serif text-2xl font-semibold">The read at a glance</h3><span className="rounded-full bg-cream px-3 py-1 text-xs capitalize text-brown">{sentiment} sentiment</span></div>{data.fakeReviewReasoning && <p className="mt-5 leading-8 text-ink/65">{data.fakeReviewReasoning}</p>}{data.redFlags?.length > 0 && <div className="mt-6 border-t border-ink/10 pt-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-amber">Signals to notice</p><ul className="mt-3 flex flex-col gap-2 text-sm text-ink/70">{data.redFlags.map((item, i) => <li key={i} className="flex gap-2"><span className="text-amber">•</span>{item}</li>)}</ul></div>}</div></div> }
function Insight({ title, items = [], tone }) { return <div className={`rounded-3xl border p-6 ${tone === 'good' ? 'border-brown/20 bg-brown text-cream' : 'border-ink/10 bg-white/65'}`}><h3 className="font-serif text-2xl font-semibold">{title}</h3><ul className="mt-5 flex flex-col gap-3 text-sm leading-6 opacity-80">{(items.length ? items : ['Nothing conclusive here.']).map((item, i) => <li key={i} className="flex gap-3"><Check size={17} className="mt-1 shrink-0 text-amber" />{item}</li>)}</ul></div> }
function ComparisonResult({ data }) { return <div className="result-stack"><div className="result-hero"><div><span className="eyebrow !text-cream/60">comparison result</span><h2 className="mt-4 font-serif text-3xl font-semibold text-cream sm:text-4xl">{data.winner || 'A closer look at both choices.'}</h2></div><div className="score"><span>decision</span><strong>✓</strong></div></div><div className="paper-card"><h3 className="font-serif text-2xl font-semibold">The short version</h3><p className="mt-5 leading-8 text-ink/65">{data.comparisonSummary || 'Both products have a case to make. Use the details below to decide what matters most to you.'}</p></div><div className="grid gap-5 md:grid-cols-2"><Insight title="Product A" items={data.productAResult ? [data.productAResult] : []} tone="soft" /><Insight title="Product B" items={data.productBResult ? [data.productBResult] : []} tone="soft" /></div></div> }

function App() { const [user, setUser] = useState(() => { try { return JSON.parse(sessionStorage.getItem('second-opinion-user')) } catch { return null } }); const [result, setResult] = useState(null); function onAuth(data) { sessionStorage.setItem('second-opinion-token', data.token); sessionStorage.setItem('second-opinion-user', JSON.stringify(data.user)); setUser(data.user) } function logout() { sessionStorage.removeItem('second-opinion-token'); sessionStorage.removeItem('second-opinion-user'); setUser(null) } return <BrowserRouter><Shell user={user} onLogout={logout}><AnimatePresence mode="wait"><Routes><Route path="/" element={<HomePage />} /><Route path="/login" element={user ? <Navigate to="/review" replace /> : <AuthPage mode="login" onAuth={onAuth} />} /><Route path="/signup" element={user ? <Navigate to="/review" replace /> : <AuthPage mode="signup" onAuth={onAuth} />} /><Route path="/review" element={<Protected user={user}><ReviewPage setResult={setResult} /></Protected>} /><Route path="/compare" element={<Protected user={user}><ComparePage setResult={setResult} /></Protected>} /><Route path="/result" element={<Protected user={user}><ResultPage result={result} /></Protected>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AnimatePresence></Shell></BrowserRouter> }

export default App
